In [2]:
from scipy import stats
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

In [41]:
import numpy as np
import pandas as pd
import seaborn as sns
from sklearn.model_selection import train_test_split
import tensorflow as tf
from tensorflow import keras

df = pd.read_csv("boston.csv", index_col=0)
df

MedInc  HouseAge  AveRooms  AveBedrms  Population  AveOccup  Latitude  \
0      8.3252      41.0  6.984127   1.023810       322.0  2.555556     37.88   
1      8.3014      21.0  6.238137   0.971880      2401.0  2.109842     37.86   
2      7.2574      52.0  8.288136   1.073446       496.0  2.802260     37.85   
3      5.6431      52.0  5.817352   1.073059       558.0  2.547945     37.85   
4      3.8462      52.0  6.281853   1.081081       565.0  2.181467     37.85   
...       ...       ...       ...        ...         ...       ...       ...   
20635  1.5603      25.0  5.045455   1.133333       845.0  2.560606     39.48   
20636  2.5568      18.0  6.114035   1.315789       356.0  3.122807     39.49   
20637  1.7000      17.0  5.205543   1.120092      1007.0  2.325635     39.43   
20638  1.8672      18.0  5.329513   1.171920       741.0  2.123209     39.43   
20639  2.3886      16.0  5.254717   1.162264      1387.0  2.616981     39.37   

       Longitude  PRICE  
0        -122.23  4.526  
1        -122.22  3.585  
2        -122.24  3.521  
3        -122.25  3.413  
4        -122.25  3.422  
...          ...    ...  
20635    -121.09  0.781  
20636    -121.21  0.771  
20637    -121.22  0.923  
20638    -121.32  0.847  
20639    -121.24  0.894  

[20640 rows x 9 columns]

In [6]:
string_columns = df.dtypes[df.dtypes == object]
string_columns

Series([], dtype: object)

In [7]:
df.describe()

MedInc      HouseAge      AveRooms     AveBedrms    Population  \
count  20640.000000  20640.000000  20640.000000  20640.000000  20640.000000   
mean       3.870671     28.639486      5.429000      1.096675   1425.476744   
std        1.899822     12.585558      2.474173      0.473911   1132.462122   
min        0.499900      1.000000      0.846154      0.333333      3.000000   
25%        2.563400     18.000000      4.440716      1.006079    787.000000   
50%        3.534800     29.000000      5.229129      1.048780   1166.000000   
75%        4.743250     37.000000      6.052381      1.099526   1725.000000   
max       15.000100     52.000000    141.909091     34.066667  35682.000000   

           AveOccup      Latitude     Longitude         PRICE  
count  20640.000000  20640.000000  20640.000000  20640.000000  
mean       3.070655     35.631861   -119.569704      2.068558  
std       10.386050      2.135952      2.003532      1.153956  
min        0.692308     32.540000   -124.350000      0.149990  
25%        2.429741     33.930000   -121.800000      1.196000  
50%        2.818116     34.260000   -118.490000      1.797000  
75%        3.282261     37.710000   -118.010000      2.647250  
max     1243.333333     41.950000   -114.310000      5.000010

In [8]:
df.isnull().sum()

MedInc        0
HouseAge      0
AveRooms      0
AveBedrms     0
Population    0
AveOccup      0
Latitude      0
Longitude     0
PRICE         0
dtype: int64

In [42]:
x = df.drop('PRICE' , axis = 1)
y = df['PRICE']

In [10]:
x_train , x_test , y_train , y_test = train_test_split(x , y)

In [11]:
x_test.shape

(5160, 8)

In [12]:
from sklearn.tree import DecisionTreeRegressor
model = DecisionTreeRegressor(max_depth=5)
model.fit(x_train, y_train)
prediction = model.predict(x_test)
prediction

array([1.66969649, 2.50779003, 1.3004879 , ..., 2.50779003, 1.66969649,
       1.91710273])

In [13]:
len(prediction)

5160

In [14]:
from sklearn.tree import DecisionTreeRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
print("Mean Squared Error:", mean_squared_error(y_test, prediction))
print("Mean Absolute Error:", mean_absolute_error(y_test, prediction))
print("R2 Score:", r2_score(y_test, prediction))

Mean Squared Error: 0.5338509922374668
Mean Absolute Error: 0.5368721761567972
R2 Score: 0.6052033386855076


In [15]:

patterens = []
accuracies = []
def FitnessFunction(ffX, ffY): # 회귀 모델을 사용한 적합도 함수
    ffx_train, ffx_test, ffy_train, ffy_test = train_test_split(ffX, ffY, test_size=0.2, random_state=42)
    model = RandomForestRegressor(n_estimators=100)
    model.fit(ffx_train, ffy_train)
    prediction = model.predict(ffx_test)
    
    mse = mean_squared_error(ffy_test, prediction)
    mae = mean_absolute_error(ffy_test, prediction)
    r2 = r2_score(ffy_test, prediction)

    return mse, mae, r2

def population_initialization(df):
    sX = df.drop('PRICE', axis=1)
    sY = df['PRICE']
    
    columns = sX.columns
    selected = np.random.randint(2, size=len(columns))
    
    modified_dataset = pd.DataFrame()
    for i in range(len(columns)):
        if selected[i] == 1:
            modified_dataset[columns[i]] = sX[columns[i]]
    
    population_initialization_display(selected)
    return FitnessFunction(modified_dataset, sY), selected

In [16]:
def population_initialization_display(selected):
    print("Pattern:", selected)

In [17]:
def generation(df):
    accuracies = []
    patterns = []
    for i in range(60):
        acc, pattern = population_initialization(df)
        accuracies.append(acc)
        patterns.append(pattern)
    return accuracies, patterns


In [18]:
def Sorting(accuracies, patterns): # Sorting both accuracies and patterns list
    combined = list(zip(accuracies, patterns))
    combined.sort(key=lambda x: x[0])  # accuracies를 기준으로 정렬
    accuracies[:], patterns[:] = zip(*combined)  # 분리하여 다시 리스트로 만듦


In [19]:

best_patteren = []
best_accuracy = 0

In [20]:
terminate_accuracy = 0


In [21]:
from sklearn.ensemble import RandomForestRegressor

def PSO(accuracies, patterns, df):
    accuracies, patterns = generation(df)
    print("Highest Accuracy Patterns And Their Accuracies\n\n")
    
    terminate_accuracy = None
    best_pattern = []
    best_accuracy = 0
    
    for _ in range(200): # Termination Criteria
        print("\n")
        print(patterns[59], accuracies[59])
        Sorting(accuracies, patterns)
        
        array = patterns
        updated = np.array(patterns)
        gbest = np.array(patterns[59])
        updated = velocity(array, updated, gbest)
        updated_accuracies = []
        
        maxlist = [max(row) for row in updated]
        
        for i in range(60):
            updated[i] = updated[i] / maxlist[i]
            updated[i] = [0 if val < 0.5 else 1 for val in updated[i]]
        
        sX = df.drop('PRICE', axis=1)
        sY = df['PRICE']
        columns = df.columns

        for i in range(60):
            modified_dataset = pd.DataFrame()
            for j in range(8):  # 8개의 열에 맞게 수정
                if updated[i][j] == 1:
                    modified_dataset[columns[j]] = sX[columns[j]]
            updated_accuracies.append(FitnessFunction(modified_dataset, sY))

        pbest = []
        pbest_accuracies = []

        for i in range(60):
            if accuracies[i] <= updated_accuracies[i]:
                pbest.append(updated[i]) 
                pbest_accuracies.append(updated_accuracies[i])
            else:
                pbest.append(patterns[i]) 
                pbest_accuracies.append(accuracies[i])

        patterns = pbest
        accuracies = pbest_accuracies
        
        if terminate_accuracy == accuracies[59]:
            print("Loop Terminated Because Of Continuous Similar Results")
            break
        
        if accuracies[59] == 80:
            break
            
        terminate_accuracy = accuracies[59]
        
    Sorting(accuracies, patterns)
    best_pattern = patterns[59]
    best_accuracy = accuracies[59]
    
    return best_pattern, best_accuracy

In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

def FitnessFunction(ffX, ffY):
    if ffX.empty or ffY.empty:
        return float('inf'), float('inf'), float('-inf')
    
    ffx_train, ffx_test, ffy_train, ffy_test = train_test_split(ffX, ffY, test_size=0.2, random_state=42)
    model = RandomForestRegressor(n_estimators=100)
    model.fit(ffx_train, ffy_train)
    prediction = model.predict(ffx_test)
    
    mse = mean_squared_error(ffy_test, prediction)
    mae = mean_absolute_error(ffy_test, prediction)
    r2 = r2_score(ffy_test, prediction)

    return mse, mae, r2

def population_initialization_display(selected):
    print("Pattern:", selected)

def population_initialization(df):
    sX = df.drop('PRICE', axis=1)
    sY = df['PRICE']
    
    columns = sX.columns
    selected = np.random.randint(2, size=len(columns))
    
    modified_dataset = pd.DataFrame()
    for i in range(len(columns)):
        if selected[i] == 1:
            modified_dataset[columns[i]] = sX[columns[i]]
    
    if modified_dataset.empty:
        return float('inf'), selected
    
    population_initialization_display(selected)
    return FitnessFunction(modified_dataset, sY), selected

def generation(df):
    accuracies = []
    patterns = []
    for i in range(60):
        acc, pattern = population_initialization(df)
        accuracies.append(acc)
        patterns.append(pattern)
    return accuracies, patterns

def Sorting(accuracies, patterns):
    combined = list(zip(accuracies, patterns))
    combined.sort(key=lambda x: x[0])  # accuracies를 기준으로 정렬
    accuracies[:], patterns[:] = zip(*combined)  # 분리하여 다시 리스트로 만듦

def velocity(array, updated, Gbest):
    c1 = 0.3
    c2 = 0.7
    r1 = np.random.random()
    r2 = np.random.random()

    vel = c1 * r1 * (updated - array) + c2 * r2 * (Gbest - array)
    updated = updated + vel
    return updated

def PSO(accuracies, patterns, df):
    accuracies, patterns = generation(df)
    print("Highest Accuracy Patterns And Their Accuracies\n\n")
    
    terminate_accuracy = None
    best_pattern = []
    best_accuracy = 0
    
    for _ in range(200): # Termination Criteria
        print("\n")
        print(patterns[59], accuracies[59])
        Sorting(accuracies, patterns)
        
        array = np.array(patterns)
        updated = np.array(patterns)
        gbest = np.array(patterns[59])
        updated = velocity(array, updated, gbest)
        updated_accuracies = []
        
        maxlist = [max(row) for row in updated]
        
        for i in range(60):
            updated[i] = updated[i] / maxlist[i]
            updated[i] = [0 if val < 0.5 else 1 for val in updated[i]]
        
        sX = df.drop('PRICE', axis=1)
        sY = df['PRICE']
        columns = df.columns

        for i in range(60):
            modified_dataset = pd.DataFrame()
            for j in range(8):  # 8개의 열에 맞게 수정
                if updated[i][j] == 1:
                    modified_dataset[columns[j]] = sX[columns[j]]
            updated_accuracies.append(FitnessFunction(modified_dataset, sY))

        pbest = []
        pbest_accuracies = []

        for i in range(60):
            if accuracies[i] <= updated_accuracies[i]:
                pbest.append(updated[i]) 
                pbest_accuracies.append(updated_accuracies[i])
            else:
                pbest.append(patterns[i]) 
                pbest_accuracies.append(accuracies[i])

        patterns = pbest
        accuracies = pbest_accuracies
        
        if terminate_accuracy == accuracies[59]:
            print("Loop Terminated Because Of Continuous Similar Results")
            break
        
        if accuracies[59] == 80:
            break
            
        terminate_accuracy = accuracies[59]
        
    Sorting(accuracies, patterns)
    best_pattern = patterns[59]
    best_accuracy = accuracies[59]
    
    return best_pattern, best_accuracy


In [86]:
accuracies = []
patterns = []
best_pattern, best_accuracy = PSO(accuracies, patterns, df)


Pattern: [1 1 1 1 0 0 0 1]
Pattern: [0 1 1 0 0 0 0 0]
Pattern: [1 1 0 1 1 0 1 0]
Pattern: [1 1 0 0 0 1 1 0]
Pattern: [1 1 1 1 1 0 1 1]
Pattern: [1 0 1 0 0 0 0 1]
Pattern: [1 0 0 0 0 1 1 0]
Pattern: [1 1 0 0 1 1 1 0]
Pattern: [0 0 0 0 1 1 1 0]
Pattern: [1 0 0 1 0 1 1 1]
Pattern: [1 0 0 0 1 1 1 0]
Pattern: [0 0 1 0 0 1 1 1]
Pattern: [1 0 0 0 1 1 1 0]
Pattern: [1 0 1 0 1 0 1 1]
Pattern: [1 1 1 0 1 1 1 1]
Pattern: [0 0 1 0 0 1 1 0]
Pattern: [1 1 1 0 1 1 0 0]
Pattern: [0 1 1 0 0 1 0 0]
Pattern: [1 1 0 1 0 1 0 1]
Pattern: [0 1 1 0 0 0 1 0]
Pattern: [1 0 0 1 1 0 0 0]
Pattern: [1 1 0 1 0 0 0 1]
Pattern: [0 0 0 0 0 0 1 1]
Pattern: [0 1 1 0 0 1 1 0]
Pattern: [1 1 0 0 0 1 1 1]
Pattern: [0 0 1 1 1 1 1 1]
Pattern: [1 1 1 0 0 1 0 0]
Pattern: [0 0 0 1 0 1 0 0]
Pattern: [1 1 1 1 1 1 0 1]
Pattern: [0 0 1 1 1 1 0 1]
Pattern: [1 1 0 0 1 1 1 0]
Pattern: [0 0 0 0 1 1 0 0]
Pattern: [0 1 0 0 0 0 0 0]
Pattern: [1 0 1 0 1 1 1 1]
Pattern: [0 1 0 0 1 0 1 0]
Pattern: [1 0 0 0 1 0 1 1]
Pattern: [0 0 0 1 1 0 0 0]
P

In [87]:
print("Best Pattern:", best_pattern)
print("Best Accuracy:", best_accuracy)
columns = df.columns[:-1]  # 'PRICE' 열을 제외한 열 이름들
print("Column Names Which Gave Best Accuracy Are:")
print("\n")
for i in range(len(best_pattern)):
    if best_pattern[i] == 1:
        print(columns[i])
print("\nBest Accuracy Is:", best_accuracy)

Best Pattern: [0. 0. 0. 1. 0. 0. 0. 0.]
Best Accuracy: (1.802668477371312, 1.051353832094687, -0.37565333213087726)
Column Names Which Gave Best Accuracy Are:


AveBedrms

Best Accuracy Is: (1.802668477371312, 1.051353832094687, -0.37565333213087726)


In [23]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

def FitnessFunction(ffX, ffY):
    if ffX.empty or ffY.empty:
        return float('inf'), float('inf'), float('-inf')
    
    ffx_train, ffx_test, ffy_train, ffy_test = train_test_split(ffX, ffY, test_size=0.2, random_state=42)
    model = RandomForestRegressor(n_estimators=100)
    model.fit(ffx_train, ffy_train)
    prediction = model.predict(ffx_test)
    
    mse = mean_squared_error(ffy_test, prediction)
    mae = mean_absolute_error(ffy_test, prediction)
    r2 = r2_score(ffy_test, prediction)

    return mse, mae, r2

def population_initialization_display(selected):
    print("Pattern:", selected)

def population_initialization(df):
    sX = df.drop('PRICE', axis=1)
    sY = df['PRICE']
    
    columns = sX.columns
    selected = np.random.randint(2, size=len(columns))
    
    modified_dataset = pd.DataFrame()
    for i in range(len(columns)):
        if selected[i] == 1:
            modified_dataset[columns[i]] = sX[columns[i]]
    
    if modified_dataset.empty:
        return float('inf'), selected
    
    population_initialization_display(selected)
    return FitnessFunction(modified_dataset, sY), selected

def generation(df, population_size):
    accuracies = []
    patterns = []
    for i in range(population_size):
        acc, pattern = population_initialization(df)
        accuracies.append(acc)
        patterns.append(pattern)
    return accuracies, patterns

def Sorting(accuracies, patterns):
    combined = list(zip(accuracies, patterns))
    combined.sort(key=lambda x: x[0])  # accuracies를 기준으로 정렬
    accuracies[:], patterns[:] = zip(*combined)  # 분리하여 다시 리스트로 만듦

def velocity(array, updated, Gbest):
    c1 = 0.3
    c2 = 0.7
    r1 = np.random.random()
    r2 = np.random.random()

    vel = c1 * r1 * (updated - array) + c2 * r2 * (Gbest - array)
    updated = updated + vel
    return updated

def PSO(accuracies, patterns, df, population_size=60):
    accuracies, patterns = generation(df, population_size)
    print("Highest Accuracy Patterns And Their Accuracies\n\n")
    
    terminate_accuracy = None
    best_pattern = []
    best_accuracy = 0
    
    for _ in range(200): # Termination Criteria
        print("\n")
        for i in range(population_size):
            print(patterns[i], accuracies[i])
        
        Sorting(accuracies, patterns)
        
        array = np.array(patterns)
        updated = np.array(patterns)
        gbest = np.array(patterns[-1])  # 마지막 개체 사용
        updated = velocity(array, updated, gbest)
        updated_accuracies = []
        
        maxlist = [max(row) for row in updated]
        
        for i in range(population_size):
            updated[i] = updated[i] / maxlist[i]
            updated[i] = [0 if val < 0.5 else 1 for val in updated[i]]
        
        sX = df.drop('PRICE', axis=1)
        sY = df['PRICE']
        columns = df.columns

        for i in range(population_size):
            modified_dataset = pd.DataFrame()
            for j in range(8):  # 8개의 열에 맞게 수정
                if updated[i][j] == 1:
                    modified_dataset[columns[j]] = sX[columns[j]]
            updated_accuracies.append(FitnessFunction(modified_dataset, sY))

        pbest = []
        pbest_accuracies = []

        for i in range(population_size):
            if accuracies[i] <= updated_accuracies[i]:
                pbest.append(updated[i]) 
                pbest_accuracies.append(updated_accuracies[i])
            else:
                pbest.append(patterns[i]) 
                pbest_accuracies.append(accuracies[i])

        patterns = pbest
        accuracies = pbest_accuracies
        
        if terminate_accuracy == accuracies[-1]:
            print("Loop Terminated Because Of Continuous Similar Results")
            break
        
        if accuracies[-1] == 80:
            break
            
        terminate_accuracy = accuracies[-1]
        
    Sorting(accuracies, patterns)
    best_pattern = patterns[-1]
    best_accuracy = accuracies[-1]
    
    return best_pattern, best_accuracy


In [24]:
accuracies = []
patterns = []
best_pattern, best_accuracy = PSO(accuracies, patterns, df)


Pattern: [0 1 1 1 1 0 0 1]
Pattern: [1 0 1 0 0 1 0 0]
Pattern: [1 0 1 0 1 0 0 1]
Pattern: [1 0 0 1 0 1 1 0]
Pattern: [1 0 0 0 0 1 1 1]
Pattern: [1 0 0 0 1 1 1 0]
Pattern: [0 0 0 1 1 0 0 1]
Pattern: [0 0 1 0 1 0 0 1]
Pattern: [1 1 1 1 0 0 0 1]
Pattern: [1 1 1 0 0 1 0 1]
Pattern: [0 1 0 1 0 0 0 1]
Pattern: [1 1 0 0 1 0 1 1]
Pattern: [1 1 1 0 0 1 0 1]
Pattern: [0 0 0 1 1 1 0 1]
Pattern: [1 1 0 0 0 0 0 1]
Pattern: [1 1 0 1 0 1 1 1]
Pattern: [1 1 0 1 0 1 0 1]
Pattern: [0 1 0 0 1 1 1 1]
Pattern: [0 1 0 1 1 0 0 0]
Pattern: [0 0 1 1 1 1 0 1]
Pattern: [0 1 1 1 1 0 1 0]
Pattern: [1 0 1 1 0 1 1 1]
Pattern: [1 0 0 1 1 1 1 1]
Pattern: [1 0 1 0 0 0 0 1]
Pattern: [0 1 1 1 1 1 0 1]
Pattern: [0 0 1 1 0 1 1 0]
Pattern: [1 1 0 0 1 1 0 1]
Pattern: [1 0 0 0 0 1 1 1]
Pattern: [1 1 1 1 1 0 0 0]
Pattern: [1 0 0 1 1 1 1 1]
Pattern: [0 1 1 1 0 0 0 1]
Pattern: [0 0 1 1 0 0 0 1]
Pattern: [0 1 0 1 0 1 1 0]
Pattern: [1 1 1 1 1 1 1 0]
Pattern: [0 0 1 1 0 0 0 0]
Pattern: [1 1 1 1 1 1 1 0]
Pattern: [0 0 0 0 0 0 0 1]
P



[0. 1. 1. 1. 0. 1. 1. 1.] (0.2242639189727193, 0.30352633921996136, 0.828859598265442)
[0. 1. 1. 1. 0. 1. 1. 1.] (0.22541114410834964, 0.3034424527131785, 0.8279841272066506)
[0. 1. 0. 0. 0. 1. 0. 0.] (1.43421314982419, 0.9192225783911266, -0.0944775056024767)
[0. 1. 0. 0. 0. 1. 0. 0.] (1.4362089541466232, 0.9193890705930365, -0.09600054486393872)
[0. 1. 0. 0. 0. 1. 0. 0.] (1.436663435901102, 0.9187590275128429, -0.09634736922337561)
[0. 1. 0. 0. 0. 1. 0. 0.] (1.4358022004427506, 0.9183843753867892, -0.09569014275999499)
[0. 1. 0. 0. 0. 1. 0. 0.] (1.4384676364498867, 0.9205911212528454, -0.0977241917106626)
[0. 1. 0. 0. 0. 1. 0. 0.] (1.4469847736010455, 0.9228556494569604, -0.10422379396658754)
[0. 1. 0. 0. 0. 1. 0. 0.] (1.442673372085459, 0.9213147298551125, -0.10093367493720318)
[0. 1. 0. 0. 0. 1. 0. 0.] (1.4406770372782924, 0.9204373891159099, -0.09941023085194778)
[0. 1. 0. 0. 0. 1. 0. 0.] (1.4461402435093662, 0.9229841172542335, -0.1035793157115521)
[0. 1. 0. 0. 0. 1. 0. 0.] (1.

Loop Terminated Because Of Continuous Similar Results


In [25]:
print("Best Pattern:", best_pattern)
print("Best Accuracy:", best_accuracy)
columns = df.columns[:-1]  # 'PRICE' 열을 제외한 열 이름들
print("Column Names Which Gave Best Accuracy Are:")
print("\n")
for i in range(len(best_pattern)):
    if best_pattern[i] == 1:
        print(columns[i])
print("\nBest Accuracy Is:", best_accuracy)

Best Pattern: [0. 1. 0. 0. 0. 1. 0. 0.]
Best Accuracy: (1.4489651398053627, 0.9226571629784687, -0.10573505208309975)
Column Names Which Gave Best Accuracy Are:


HouseAge
AveOccup

Best Accuracy Is: (1.4489651398053627, 0.9226571629784687, -0.10573505208309975)


# CNN

In [43]:
x_train , x_test , y_train , y_test = train_test_split(x , y)

In [82]:
def build_cnn(input_shape):
    """ CNN 모델을 빌드하고 컴파일하는 함수 """
    model = Sequential()
    model.add(Conv2D(32, kernel_size=(3, 1), activation='relu', input_shape=input_shape))
    model.add(MaxPooling2D(pool_size=(3, 1)))
    model.add(Flatten())
    model.add(Dense(128, activation='relu'))
    model.add(Dense(1, activation='linear'))
    model.compile(optimizer='adam', loss='mean_squared_error', metrics=['mean_absolute_error', 'mean_squared_error'])
    return model

In [90]:
feature_count = x.shape[1]
x = np.array(x).reshape((-1, feature_count, 1, 1))  # (samples, features, 1, 1) 형태로 재구성
X_train, X_test, Y_train, Y_test = train_test_split(x, y, test_size=0.2, random_state=42)
    
input_shape = (feature_count, 1, 1)
model = build_cnn(input_shape)
model.fit(X_train, Y_train, epochs=10, batch_size=16, verbose=1)
    
prediction = model.predict(X_test)
mse = mean_squared_error(Y_test, prediction)
mae = mean_absolute_error(Y_test, prediction)
r2 = r2_score(Y_test, prediction)


Epoch 1/10
1032/1032 [==============================] - 3s 2ms/step - loss: 77.8107 - mean_absolute_error: 2.5041 - mean_squared_error: 77.8107
Epoch 2/10
1032/1032 [==============================] - 2s 2ms/step - loss: 25.4583 - mean_absolute_error: 2.0310 - mean_squared_error: 25.4583
Epoch 3/10
1032/1032 [==============================] - 2s 2ms/step - loss: 293.3281 - mean_absolute_error: 3.1339 - mean_squared_error: 293.3281
Epoch 4/10
1032/1032 [==============================] - 2s 2ms/step - loss: 0.7391 - mean_absolute_error: 0.6565 - mean_squared_error: 0.7391
Epoch 5/10
1032/1032 [==============================] - 2s 2ms/step - loss: 2.1727 - mean_absolute_error: 0.8160 - mean_squared_error: 2.1727
Epoch 6/10
1032/1032 [==============================] - 2s 2ms/step - loss: 1.2328 - mean_absolute_error: 0.7420 - mean_squared_error: 1.2328
Epoch 7/10
1032/1032 [==============================] - 2s 2ms/step - loss: 4.1651 - mean_absolute_error: 1.0828 - mean_squared_error: 4.165

In [94]:
print(mse)
print(mae)
print(r2)

1.1822150982691513
0.8770011573400597
0.09782738221454845


In [85]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense

def build_cnn(input_shape):
    """ CNN 모델을 빌드하고 컴파일하는 함수 """
    model = Sequential()
    model.add(Conv2D(32, kernel_size=(1, 1), activation='relu', input_shape=input_shape))
    model.add(MaxPooling2D(pool_size=(1, 1)))
    model.add(Flatten())
    model.add(Dense(128, activation='relu'))
    model.add(Dense(1, activation='linear'))
    model.compile(optimizer='adam', loss='mean_squared_error', metrics=['mean_absolute_error', 'mean_squared_error'])
    return model

def FitnessFunction(ffX, ffY):
    """ 주어진 데이터로 CNN 모델을 훈련시키고 피트니스 값을 반환하는 함수 """
    if ffX.empty or ffY.empty or len(ffX) != len(ffY):
        return float('inf'), float('inf'), float('-inf')
    
    # CNN 입력을 위해 데이터 재구성
    feature_count = ffX.shape[1]
    ffX = np.array(ffX).reshape((-1, feature_count, 1, 1))  # (samples, features, 1, 1) 형태로 재구성
    ffX_train, ffX_test, ffY_train, ffY_test = train_test_split(ffX, ffY, test_size=0.2, random_state=42)
    
    input_shape = (feature_count, 1, 1)
    model = build_cnn(input_shape)
    model.fit(ffX_train, ffY_train, epochs=10, batch_size=16, verbose=0)
    
    prediction = model.predict(ffX_test)
    mse = mean_squared_error(ffY_test, prediction)
    mae = mean_absolute_error(ffY_test, prediction)
    r2 = r2_score(ffY_test, prediction)

    return mse, mae, r2

def population_initialization_display(selected):
    """ 선택된 패턴을 출력하는 함수 """
    print("Pattern:", selected)

def population_initialization(df):
    """ 초기 개체군을 생성하고 피트니스 값을 계산하는 함수 """
    sX = df.drop('PRICE', axis=1)
    sY = df['PRICE']
    
    columns = sX.columns
    selected = np.random.randint(2, size=len(columns))
    
    modified_dataset = pd.DataFrame()
    for i in range(len(columns)):
        if selected[i] == 1:
            modified_dataset[columns[i]] = sX[columns[i]]
    
    modified_dataset = modified_dataset.dropna()  # 결측치 제거로 데이터 길이 맞춤
    
    # modified_dataset과 sY의 길이가 일치하는지 확인
    if len(modified_dataset) != len(sY):
        return float('inf'), selected
    
    population_initialization_display(selected)
    return FitnessFunction(modified_dataset, sY), selected

def generation(df, population_size):
    """ 초기 개체군을 생성하는 함수 """
    accuracies = []
    patterns = []
    for i in range(population_size):
        acc, pattern = population_initialization(df)
        accuracies.append(acc)
        patterns.append(pattern)
    return accuracies, patterns

def Sorting(accuracies, patterns):
    """ 개체군을 피트니스 값에 따라 정렬하는 함수 """
    combined = list(zip(accuracies, patterns))
    combined.sort(key=lambda x: x[0])  # accuracies를 기준으로 정렬
    accuracies[:], patterns[:] = zip(*combined)  # 분리하여 다시 리스트로 만듦

def velocity(array, updated, Gbest):
    """ 입자의 속도를 업데이트하는 함수 """
    c1 = 0.3
    c2 = 0.7
    r1 = np.random.random()
    r2 = np.random.random()

    vel = c1 * r1 * (updated - array) + c2 * r2 * (Gbest - array)
    updated = updated + vel
    return updated

def PSO(accuracies, patterns, df, population_size=60):
    """ PSO 알고리즘을 실행하여 최적의 패턴과 정확도를 찾는 함수 """
    accuracies, patterns = generation(df, population_size)
    print("Highest Accuracy Patterns And Their Accuracies\n\n")
    
    terminate_accuracy = None
    best_pattern = []
    best_accuracy = 0
    
    for _ in range(200): # Termination Criteria
        print("\n")
        for i in range(population_size):
            print(f"{patterns[i]} ({accuracies[i][0]:.3f}, {accuracies[i][1]:.3f}, {accuracies[i][2]:.3f})")
        
        Sorting(accuracies, patterns)
        
        array = np.array(patterns)
        updated = np.array(patterns)
        gbest = np.array(patterns[-1])  # 마지막 개체 사용
        updated = velocity(array, updated, gbest)
        updated_accuracies = []
        
        maxlist = [max(row) for row in updated]
        
        for i in range(population_size):
            updated[i] = updated[i] / maxlist[i]
            updated[i] = [0 if val < 0.5 else 1 for val in updated[i]]
        
        sX = df.drop('PRICE', axis=1)
        sY = df['PRICE']
        columns = df.columns

        for i in range(population_size):
            modified_dataset = pd.DataFrame()
            for j in range(8):  # 8개의 열에 맞게 수정
                if updated[i][j] == 1:
                    modified_dataset[columns[j]] = sX[columns[j]]
            if len(modified_dataset) == len(sY):
                updated_accuracies.append(FitnessFunction(modified_dataset, sY))
            else:
                updated_accuracies.append((float('inf'), float('inf'), float('-inf')))

        pbest = []
        pbest_accuracies = []

        for i in range(population_size):
            if accuracies[i] <= updated_accuracies[i]:
                pbest.append(updated[i]) 
                pbest_accuracies.append(updated_accuracies[i])
            else:
                pbest.append(patterns[i]) 
                pbest_accuracies.append(accuracies[i])

        patterns = pbest
        accuracies = pbest_accuracies
        
        if terminate_accuracy == accuracies[-1]:
            print("Loop Terminated Because Of Continuous Similar Results")
            break
        
        if accuracies[-1][2] >= 0.8:
            break
            
        terminate_accuracy = accuracies[-1]
        
    Sorting(accuracies, patterns)
    best_pattern = patterns[-1]
    best_accuracy = accuracies[-1]
    
    return best_pattern, best_accuracy

In [86]:
accuracies = []
patterns = []
best_pattern, best_accuracy = PSO(accuracies, patterns, df)

Pattern: [0 1 0 0 0 0 1 1]


2024-06-30 06:05:59.328911: I tensorflow/compiler/xla/stream_executor/cuda/cuda_dnn.cc:442] Loaded cuDNN version 8907
2024-06-30 06:06:00.608123: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x7f4239271e10 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2024-06-30 06:06:00.608164: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): CUDA GPU, Compute Capability 8.0
2024-06-30 06:06:00.608175: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (1): CUDA GPU, Compute Capability 8.0
2024-06-30 06:06:00.614755: I tensorflow/compiler/mlir/tensorflow/utils/dump_mlir_util.cc:269] disabling MLIR crash reproducer, set env var `MLIR_CRASH_REPRODUCER_DIRECTORY` to enable.
2024-06-30 06:06:00.722962: I ./tensorflow/compiler/jit/device_compiler.h:186] Compiled cluster using XLA!  This line is logged at most once for the lifetime of the process.


129/129 [==============================] - 0s 1ms/step
Pattern: [0 1 1 0 0 1 1 1]
129/129 [==============================] - 0s 970us/step
Pattern: [1 1 1 1 0 0 1 0]
129/129 [==============================] - 0s 1ms/step
Pattern: [0 1 1 1 1 0 1 0]
129/129 [==============================] - 0s 949us/step
Pattern: [1 1 0 0 0 0 0 1]
129/129 [==============================] - 0s 953us/step
Pattern: [1 1 0 0 0 0 1 1]
129/129 [==============================] - 0s 978us/step
Pattern: [0 1 1 0 1 0 0 1]
129/129 [==============================] - 0s 997us/step
Pattern: [0 1 1 1 0 0 1 1]
129/129 [==============================] - 0s 989us/step
Pattern: [1 0 1 1 0 0 1 1]
129/129 [==============================] - 0s 952us/step
Pattern: [1 1 0 1 0 0 0 0]
129/129 [==============================] - 0s 977us/step
Pattern: [1 0 0 0 0 1 1 0]
129/129 [==============================] - 0s 954us/step
Pattern: [0 1 0 0 0 0 0 1]
129/129 [==============================] - 0s 996us/step
Pattern: [0 0 1 1 0 1 0

129/129 [==============================] - 0s 961us/step


[1. 0. 0. 0. 0. 1. 1. 1.] (0.564, 0.565, 0.570)
[1. 1. 0. 0. 0. 1. 1. 1.] (0.636, 0.574, 0.515)
[1. 1. 1. 1. 0. 0. 1. 0.] (0.585, 0.564, 0.553)
[1. 1. 1. 1. 0. 0. 0. 1.] (0.597, 0.552, 0.545)
[1 0 0 0 0 1 1 0] (0.610, 0.559, 0.535)
[1 1 1 0 0 0 1 0] (0.613, 0.600, 0.532)
[1. 1. 0. 1. 0. 0. 1. 0.] (0.637, 0.571, 0.514)
[1 1 1 1 0 0 0 1] (0.624, 0.551, 0.524)
[1. 1. 0. 0. 0. 0. 1. 1.] (0.642, 0.627, 0.510)
[1. 0. 1. 1. 0. 0. 1. 1.] (0.637, 0.596, 0.514)
[1 1 1 1 0 0 0 1] (0.636, 0.549, 0.515)
[1. 1. 1. 0. 1. 1. 0. 1.] (1.071, 0.746, 0.183)
[1. 0. 1. 0. 0. 0. 0. 1.] (0.683, 0.569, 0.479)
[1. 1. 0. 0. 1. 0. 0. 1.] (0.687, 0.606, 0.476)
[1 0 1 1 0 0 1 1] (0.661, 0.619, 0.495)
[1 1 0 0 0 0 0 1] (0.668, 0.641, 0.491)
[1 1 0 1 0 0 0 0] (0.680, 0.586, 0.481)
[1. 0. 1. 1. 1. 0. 1. 1.] (0.723, 0.685, 0.448)
[1 0 0 0 0 0 0 0] (0.702, 0.616, 0.464)
[1 0 0 1 0 0 1 1] (0.714, 0.588, 0.455)
[0. 0. 1. 1. 0. 1. 1. 1.] (1.090, 0.797, 0.168)
[0. 1

129/129 [==============================] - 0s 948us/step


[1. 0. 0. 0. 0. 1. 1. 1.] (0.583, 0.596, 0.555)
[1. 1. 1. 1. 0. 0. 1. 0.] (0.605, 0.599, 0.538)
[1. 1. 1. 1. 0. 0. 0. 1.] (0.597, 0.552, 0.545)
[1 0 0 0 0 1 1 0] (0.610, 0.559, 0.535)
[1 1 1 0 0 0 1 0] (0.613, 0.600, 0.532)
[1 1 1 1 0 0 0 1] (0.624, 0.551, 0.524)
[1 1 1 1 0 0 0 1] (0.636, 0.549, 0.515)
[1. 1. 0. 0. 0. 1. 1. 1.] (0.636, 0.574, 0.515)
[1. 1. 1. 1. 1. 1. 1. 0.] (1.017, 0.734, 0.224)
[1. 0. 1. 1. 0. 0. 1. 1.] (0.700, 0.680, 0.466)
[1. 1. 1. 0. 1. 1. 1. 1.] (0.689, 0.655, 0.474)
[1. 0. 1. 1. 0. 0. 1. 1.] (0.677, 0.632, 0.484)
[1 1 0 0 0 0 0 1] (0.668, 0.641, 0.491)
[1. 1. 1. 1. 1. 1. 0. 0.] (0.688, 0.612, 0.475)
[1. 0. 1. 0. 0. 0. 0. 1.] (0.683, 0.569, 0.479)
[1. 1. 0. 0. 1. 0. 0. 1.] (0.687, 0.606, 0.476)
[1. 0. 1. 0. 1. 1. 0. 0.] (0.763, 0.622, 0.418)
[1. 0. 1. 1. 1. 1. 1. 1.] (0.726, 0.623, 0.446)
[1. 0. 1. 1. 1. 0. 1. 1.] (0.738, 0.676, 0.437)
[0. 0. 1. 1. 0. 1. 0. 0.] (0.968, 0.752, 0.262)
[0. 1. 1. 1. 0. 0. 1.

In [87]:
columns = df.columns[:-1]  # 'PRICE' 열을 제외한 열 이름들
print("Column Names Which Gave Best Accuracy Are:")
print("\n")
for i in range(len(best_pattern)):
    if best_pattern[i] == 1:
        print(columns[i])
print("\nBest Accuracy Is:", best_accuracy)

Column Names Which Gave Best Accuracy Are:


MedInc
HouseAge
AveRooms
Population
AveOccup
Longitude

Best Accuracy Is: (145.13440394575846, 7.96289221880068, -109.75504392574271)
